-- Seed 90-day Leadership Reboot curriculum
-- This creates the daily lessons based on the SIGNAL model

INSERT INTO public.daily_lessons (day_number, focus_area, focus_reframe_technique, leader_example, leader_context, thought_to_work_on, action_for_today)
VALUES
-- Week 1: Self-Awareness Foundation (Days 1-7)
(1, 'Self-Awareness', 'The Mirror Exercise', 'Satya Nadella', 'When Nadella became CEO of Microsoft, his first move was understanding his own leadership blind spots.', 'What assumptions about leadership am I carrying that might be outdated?', 'Write down 3 leadership beliefs you hold and question where each came from.'),
(2, 'Self-Awareness', 'Emotional Inventory', 'Brené Brown', 'Brown''s research shows that leaders who name their emotions lead with 40% more effectiveness.', 'How often do I pause to identify what I''m actually feeling before reacting?', 'Set 3 phone reminders today to pause and name your current emotion.'),
(3, 'Self-Awareness', 'Feedback Integration', 'Ray Dalio', 'Dalio built Bridgewater on radical transparency, starting with his own willingness to receive critical feedback.', 'When was the last time I genuinely thanked someone for difficult feedback?', 'Ask one trusted colleague: What''s one thing I could do better as a leader?'),
(4, 'Self-Awareness', 'Values Alignment Check', 'Howard Schultz', 'Schultz returned to Starbucks when he saw the company drifting from its core values.', 'Are my daily decisions aligned with what I say matters most?', 'List your top 3 values. Review yesterday''s calendar against them.'),
(5, 'Self-Awareness', 'Energy Mapping', 'Arianna Huffington', 'After collapsing from exhaustion, Huffington rebuilt her approach to sustainable leadership.', 'What activities drain me vs. energize me, and am I honest about this?', 'Track your energy levels hourly today. Note patterns.'),
(6, 'Self-Awareness', 'Strength Blindness', 'Marcus Buckingham', 'Buckingham''s research shows we spend 80% of development time on weaknesses, not strengths.', 'Am I building on my natural strengths or constantly fighting my nature?', 'Identify one strength you''ve neglected. Use it intentionally today.'),
(7, 'Self-Awareness', 'Weekly Reflection', 'Bill Gates', 'Gates takes "Think Weeks" twice yearly for deep self-reflection and strategic thinking.', 'What patterns am I noticing in myself this week?', 'Spend 15 minutes journaling about your leadership week.'),

-- Week 2: Influence Without Authority (Days 8-14)
(8, 'Influence', 'The Pull vs. Push', 'Simon Sinek', 'Sinek''s "Start With Why" demonstrates that inspiration outperforms instruction.', 'Do I lead by telling or by inspiring? What''s the ratio?', 'In your next meeting, replace one directive with a compelling question.'),
(9, 'Influence', 'Strategic Listening', 'Indra Nooyi', 'Nooyi was known for writing letters to parents of her executives, showing deep personal attention.', 'When I listen, am I waiting to respond or truly seeking to understand?', 'In 3 conversations today, summarize what you heard before responding.'),
(10, 'Influence', 'Building Coalitions', 'Abraham Lincoln', 'Lincoln''s "Team of Rivals" approach turned competitors into collaborators.', 'Who disagrees with me that I should be learning from instead of dismissing?', 'Identify one person who sees things differently. Schedule coffee with them.'),
(11, 'Influence', 'Executive Presence', 'Christine Lagarde', 'Lagarde commands rooms without raising her voice through composed confidence.', 'Does my presence invite engagement or create distance?', 'Record yourself in a meeting (with permission). Notice your body language.'),
(12, 'Influence', 'The Currency of Trust', 'Warren Buffett', 'Buffett says it takes 20 years to build a reputation and 5 minutes to ruin it.', 'Am I making more deposits or withdrawals in my trust accounts?', 'Make one unexpected trust deposit with a colleague today.'),
(13, 'Influence', 'Narrative Crafting', 'Steve Jobs', 'Jobs didn''t sell products; he sold stories about the future.', 'What story am I telling about where we''re going? Is it compelling?', 'Reframe one initiative you''re leading as a story with a hero (your team).'),
(14, 'Influence', 'Influence Inventory', 'Keith Ferrazzi', 'Ferrazzi maps relationships like a scientist, understanding the network effect.', 'Who influences the influencers in my organization?', 'Draw your influence map. Identify one gap to address this week.'),

-- Week 3: Growth Mindset (Days 15-21)
(15, 'Growth Mindset', 'Fixed vs. Growth Recognition', 'Carol Dweck', 'Dweck''s research shows mindset is the #1 predictor of achievement over time.', 'In what areas have I declared myself "not a natural" and stopped growing?', 'Pick one skill you''ve avoided. Commit to 15 minutes of practice today.'),
(16, 'Growth Mindset', 'Failure Reframing', 'Sara Blakely', 'Blakely''s father asked nightly: "What did you fail at today?" celebrating attempts.', 'Do I fear failure so much that I play it safe?', 'Intentionally try something where failure is likely. Note what you learn.'),
(17, 'Growth Mindset', 'The Learning Loop', 'Jeff Bezos', 'Bezos requires teams to write 6-page memos forcing clear thinking and learning.', 'After projects end, do I systematically extract and share learnings?', 'Write a one-page "What I Learned" memo about a recent project.'),
(18, 'Growth Mindset', 'Curiosity as Strategy', 'Reed Hastings', 'Hastings disrupted his own DVD business because he stayed curious about the future.', 'What would I explore if I had no fear of looking unknowledgeable?', 'Ask 5 "Why?" questions in meetings today. Go deeper than usual.'),
(19, 'Growth Mindset', 'Embracing "Yet"', 'Oprah Winfrey', 'Winfrey was fired from her first TV job. She added "yet" to every setback.', 'What am I saying "I can''t" about that should be "I can''t yet"?', 'Catch yourself saying "I can''t" today. Add "yet" and notice the shift.'),
(20, 'Growth Mindset', 'Teaching to Learn', 'Richard Feynman', 'Feynman''s technique: Teach concepts simply to truly understand them.', 'What do I think I know well but have never taught to someone else?', 'Teach one concept you know to a colleague or mentee today.'),
(21, 'Growth Mindset', 'Growth Mindset Team Culture', 'Amy Edmondson', 'Edmondson''s psychological safety research shows growth requires safe experimentation.', 'Does my team feel safe to experiment and fail?', 'Share one of your recent failures with your team and what you learned.'),

-- Week 4: Navigating Complexity (Days 22-28)
(22, 'Navigating Complexity', 'Systems Thinking', 'Peter Senge', 'Senge''s "Fifth Discipline" teaches that local solutions create global problems.', 'When I solve problems, do I consider second and third-order effects?', 'For one decision today, map out 3 levels of potential ripple effects.'),
(23, 'Navigating Complexity', 'Embracing Ambiguity', 'Angela Merkel', 'Merkel led through multiple crises by staying calm in uncertainty.', 'How comfortable am I saying "I don''t know" to my team?', 'Practice saying "I don''t know, let''s figure it out together" once today.'),
(24, 'Navigating Complexity', 'Decision-Making Under Uncertainty', 'Annie Duke', 'Duke, former poker champion, teaches that good decisions can have bad outcomes.', 'Do I judge my decisions by outcomes or by process quality?', 'Review a recent decision. Evaluate the process, not just the result.'),
(25, 'Navigating Complexity', 'Paradox Management', 'F. Scott Fitzgerald', 'Fitzgerald said intelligence is holding two opposing ideas simultaneously.', 'What apparent contradictions in my work might both be true?', 'List 3 tensions you manage. Consider how both sides might be right.'),
(26, 'Navigating Complexity', 'Rapid Adaptation', 'Reed Hastings', 'Netflix''s culture deck says: "We''re a team, not a family" - adapt or perish.', 'How quickly can I let go of plans when circumstances change?', 'Identify one plan you''re holding onto. Ask if it still makes sense.'),
(27, 'Navigating Complexity', 'Information Filtering', 'Nate Silver', 'Silver distinguishes signal from noise in prediction and decision-making.', 'What noise am I treating as signal? What signal am I missing?', 'Review your information diet. Cut one noise source. Add one signal source.'),
(28, 'Navigating Complexity', 'Complexity Week Reflection', 'General Stanley McChrystal', 'McChrystal transformed military leadership from command-and-control to team of teams.', 'Where am I trying to control what should be distributed?', 'Identify one decision you make that your team could make instead.'),

-- Week 5: Authentic Communication (Days 29-35)
(29, 'Communication', 'Radical Candor', 'Kim Scott', 'Scott''s framework: Care personally while challenging directly.', 'Am I so focused on being liked that I avoid necessary tough conversations?', 'Have one conversation today where you care AND challenge.'),
(30, 'Communication', 'The Power of Pause', 'Tim Cook', 'Cook is known for long, thoughtful pauses that communicate contemplation.', 'Do I fill silence because I''m uncomfortable, or use it strategically?', 'In meetings today, count to 5 before responding to important questions.'),
(31, 'Communication', 'Message Simplification', 'Jeff Weiner', 'Weiner says "Simple can be harder than complex" but it''s always more effective.', 'Can I explain our strategy to a new employee in 2 minutes?', 'Take your most complex initiative. Simplify it to 3 bullets.'),
(32, 'Communication', 'Active Listening Mastery', 'Sheryl Sandberg', 'Sandberg schedules "listening tours" to stay connected to organizational reality.', 'When did I last change my mind based on what someone told me?', 'In 3 conversations, focus only on understanding. No advice-giving.'),
(33, 'Communication', 'Non-Verbal Awareness', 'Amy Cuddy', 'Cuddy''s research shows body language affects not just others, but ourselves.', 'What is my body communicating when I think I''m neutral?', 'Ask a trusted colleague what your body language says in meetings.'),
(34, 'Communication', 'Difficult Conversations', 'Douglas Stone', 'Stone''s "Difficult Conversations" shows we avoid what matters most.', 'What conversation am I avoiding that would make a real difference?', 'Schedule that conversation for this week. Prepare with empathy.'),
(35, 'Communication', 'Communication Audit', 'Patrick Lencioni', 'Lencioni says leaders must repeat messages 7x before they land.', 'Am I under-communicating the things that matter most?', 'Ask 3 team members to share your top priority back to you.'),

-- Week 6: Leading Through Change (Days 36-42)
(36, 'Change Leadership', 'Creating Urgency', 'John Kotter', 'Kotter''s first step of change: Establish a genuine sense of urgency.', 'Have I made the case for change compelling enough?', 'Rewrite your change case as if your job depended on people believing it.'),
(37, 'Change Leadership', 'Vision Casting', 'Martin Luther King Jr.', 'King''s "I Have a Dream" painted a vivid picture of a better future.', 'Is my vision concrete enough that people can see themselves in it?', 'Describe your vision using sensory language. What does it look, feel, sound like?'),
(38, 'Change Leadership', 'Building the Guiding Coalition', 'Lou Gerstner', 'Gerstner transformed IBM by building a coalition of believers across silos.', 'Who are my change champions? Have I empowered them enough?', 'Identify 3 informal influencers. Have a change conversation with each.'),
(39, 'Change Leadership', 'Quick Wins Strategy', 'Teresa Amabile', 'Amabile''s "Progress Principle" shows small wins fuel motivation.', 'Am I celebrating progress or only focusing on the final destination?', 'Identify and publicly celebrate one small win today.'),
(40, 'Change Leadership', 'Resistance Reframing', 'William Bridges', 'Bridges teaches that people don''t resist change; they resist loss.', 'What losses are my people experiencing that I haven''t acknowledged?', 'Ask someone resistant to change: What will you miss about the old way?'),
(41, 'Change Leadership', 'Sustaining Momentum', 'Chip & Dan Heath', 'The Heaths'' "Switch" shows that what looks like resistance is often exhaustion.', 'Am I asking too much change too fast?', 'Review your change initiatives. What could you pause to reduce fatigue?'),
(42, 'Change Leadership', 'Institutionalizing Change', 'Edgar Schein', 'Schein says culture eats strategy for breakfast - change must become culture.', 'What structures, systems, or rituals would make this change stick?', 'Design one ritual that would reinforce your desired change.'),

-- Week 7: Team Excellence (Days 43-49)
(43, 'Team Excellence', 'Team Composition', 'Patrick Lencioni', 'Lencioni''s "Ideal Team Player" emphasizes humble, hungry, and smart.', 'Do I have the right people, or am I hoping wrong people will change?', 'Audit your team against humble, hungry, smart. Note gaps.'),
(44, 'Team Excellence', 'Psychological Safety', 'Amy Edmondson', 'Google''s Project Aristotle found psychological safety is #1 predictor of team success.', 'Would my team members take a risk without fearing embarrassment?', 'Share a mistake you made this week and what you learned.'),
(45, 'Team Excellence', 'Clarifying Roles', 'Patrick Lencioni', 'Lencioni says 75% of cross-functional teams are dysfunctional due to unclear roles.', 'Does everyone on my team know exactly what they''re responsible for?', 'Ask each team member to write their top 3 responsibilities. Compare notes.'),
(46, 'Team Excellence', 'Productive Conflict', 'Liane Davey', 'Davey says teams need to "fight well" - conflict around ideas, not people.', 'Does my team avoid healthy conflict to maintain false harmony?', 'In your next meeting, explicitly invite disagreement on an important topic.'),
(47, 'Team Excellence', 'Accountability Culture', 'Patrick Lencioni', 'Lencioni teaches that peer accountability is stronger than boss accountability.', 'Does my team hold each other accountable, or only look to me?', 'Facilitate a conversation where team members set expectations for each other.'),
(48, 'Team Excellence', 'Results Focus', 'John Doerr', 'Doerr''s OKR system keeps Google aligned and focused on what matters.', 'Are we measuring activity or outcomes?', 'Review your team metrics. Eliminate one activity metric. Add one outcome metric.'),
(49, 'Team Excellence', 'Team Health Check', 'Jim Collins', 'Collins says "Get the right people on the bus, wrong people off, right people in right seats."', 'If I were hiring my team fresh today, would I rehire everyone?', 'Have a candid conversation with yourself about team composition.'),

-- Week 8: Strategic Thinking (Days 50-56)
(50, 'Strategic Thinking', 'Long-Term vs. Short-Term', 'Jeff Bezos', 'Bezos optimizes for the long term, famously saying "It''s always Day 1."', 'Am I sacrificing long-term advantage for short-term comfort?', 'Identify one short-term decision. Reconsider it with a 10-year lens.'),
(51, 'Strategic Thinking', 'Competitive Awareness', 'Michael Porter', 'Porter''s Five Forces helps leaders see the full competitive landscape.', 'What am I missing by only focusing on direct competitors?', 'Analyze one threat from a non-traditional competitor or substitute.'),
(52, 'Strategic Thinking', 'Resource Allocation', 'Roger Martin', 'Martin says strategy is about making choices - specifically, what NOT to do.', 'What am I doing that I should stop to free resources for better things?', 'List 3 initiatives. Choose one to stop or reduce investment in.'),
(53, 'Strategic Thinking', 'Scenario Planning', 'Pierre Wack', 'Wack developed scenario planning at Shell, preparing for multiple futures.', 'Am I planning for one future or preparing for several?', 'Imagine 3 different futures for your industry. How would you prepare for each?'),
(54, 'Strategic Thinking', 'Customer Obsession', 'Jeff Bezos', 'Bezos starts with the customer and works backward, not from capabilities.', 'When did I last surprise and delight a customer?', 'Spend 30 minutes today talking directly with a customer or end user.'),
(55, 'Strategic Thinking', 'Innovation Balance', 'Clayton Christensen', 'Christensen''s "Innovator''s Dilemma" shows how success breeds failure.', 'Am I investing enough in disruptive vs. sustaining innovation?', 'Identify one resource you could shift from optimization to experimentation.'),
(56, 'Strategic Thinking', 'Strategy Communication', 'Roger Martin', 'Martin says if your strategy fits on a page, you might actually execute it.', 'Can my team articulate our strategy without me?', 'Ask 3 team members to explain our strategy. Note the consistency.'),

-- Week 9: Developing Others (Days 57-63)
(57, 'Developing Others', 'Coaching vs. Directing', 'Michael Bungay Stanier', 'Stanier''s "Coaching Habit" shows asking beats telling for development.', 'How much of my leadership is telling vs. asking?', 'Replace 5 statements with questions today. Track the difference.'),
(58, 'Developing Others', 'Feedback as Gift', 'Kim Scott', 'Scott says feedback should be so immediate it becomes unremarkable.', 'Do I give feedback frequently enough that it''s not a big deal?', 'Give 3 pieces of real-time feedback today - both praise and constructive.'),
(59, 'Developing Others', 'Delegation as Development', 'Linda Hill', 'Hill''s research shows managers fail by delegating tasks, not development.', 'Am I delegating work or delegating growth opportunities?', 'Identify one task you do that could stretch a team member. Delegate it.'),
(60, 'Developing Others', 'Career Conversations', 'Julie Zhuo', 'Zhuo emphasizes understanding what people want, not assuming.', 'When did I last have a real conversation about someone''s aspirations?', 'Schedule a career conversation with one team member this week.'),
(61, 'Developing Others', 'Creating Learning Cultures', 'Peter Senge', 'Senge''s "Learning Organization" shows competitive advantage comes from learning speed.', 'Does my team learn faster than our competition?', 'Implement one practice that would increase team learning speed.'),
(62, 'Developing Others', 'Succession Thinking', 'Ram Charan', 'Charan says leaders should always be developing their replacement.', 'If I got promoted tomorrow, who would step into my role?', 'Identify your successor. Start a development conversation with them.'),
(63, 'Developing Others', 'Development Week Reflection', 'Marshall Goldsmith', 'Goldsmith says "What got you here won''t get you there" - continuous development is key.', 'Am I investing as much in others'' development as my own?', 'Calculate time spent developing others vs. yourself. Adjust if needed.'),

-- Week 10: Resilience & Energy (Days 64-70)
(64, 'Resilience', 'Energy Management', 'Tony Schwartz', 'Schwartz proves energy, not time, is the fundamental currency of performance.', 'Am I managing my time but ignoring my energy?', 'Track your energy through the day. Identify your peak hours.'),
(65, 'Resilience', 'Recovery Rituals', 'Jim Loehr', 'Loehr trains executives like athletes - stress + recovery = growth.', 'Do I have real recovery built into my routine, or do I just crash?', 'Design one deliberate recovery ritual for your day.'),
(66, 'Resilience', 'Stress Reframing', 'Kelly McGonigal', 'McGonigal''s research shows stress helps when we believe it helps.', 'Do I view stress as threat or challenge?', 'When stress hits today, say "I''m excited" instead of "I''m stressed."'),
(67, 'Resilience', 'Boundary Setting', 'Brené Brown', 'Brown says clear is kind, unclear is unkind - especially with boundaries.', 'What boundary have I failed to set that''s costing me?', 'Set one clear boundary today. Communicate it directly.'),
(68, 'Resilience', 'Support Networks', 'John Cacioppo', 'Cacioppo''s research shows loneliness is as dangerous as smoking for executives.', 'Who do I talk to when leadership is hard?', 'Reach out to one peer leader for a real conversation. Not networking - connection.'),
(69, 'Resilience', 'Purpose Reconnection', 'Viktor Frankl', 'Frankl survived Auschwitz by finding meaning. Purpose fuels resilience.', 'What is my deeper purpose beyond the job title?', 'Write one paragraph about why your work matters beyond the obvious.'),
(70, 'Resilience', 'Resilience Assessment', 'Martin Seligman', 'Seligman''s positive psychology shows optimism can be learned.', 'Am I building sustainable resilience or just pushing through?', 'Rate your current resilience 1-10. Identify one practice to improve it.'),

-- Week 11: Innovation Mindset (Days 71-77)
(71, 'Innovation', 'Questioning Assumptions', 'Elon Musk', 'Musk uses first-principles thinking to challenge industry assumptions.', 'What "that''s just how it''s done" assumptions am I accepting?', 'List 3 standard practices in your work. Question each from first principles.'),
(72, 'Innovation', 'Diverse Perspectives', 'Frans Johansson', 'Johansson''s "Medici Effect" shows innovation happens at intersections.', 'Am I surrounded by people who think like me?', 'Have a conversation with someone from a completely different field today.'),
(73, 'Innovation', 'Safe Experimentation', 'Eric Ries', 'Ries'' "Lean Startup" shows the fastest learner wins.', 'What small experiment could test a big assumption?', 'Design one small, low-risk experiment to run this week.'),
(74, 'Innovation', 'Creative Constraints', 'Marissa Mayer', 'Mayer says constraints drive creativity at Google.', 'Am I using constraints as excuses or as creative fuel?', 'Take one constraint you''re complaining about. Brainstorm how it could help.'),
(75, 'Innovation', 'Pattern Recognition', 'Steve Jobs', 'Jobs said creativity is connecting things - seeing patterns others miss.', 'What patterns am I seeing that others might be missing?', 'Look for one pattern connecting different problems you''re facing.'),
(76, 'Innovation', 'Kill Your Darlings', 'Ed Catmull', 'Catmull at Pixar teaches that protecting mediocre ideas kills great ones.', 'What am I protecting that should die to make room for better?', 'Identify one project or practice that''s "good enough" but blocking great.'),
(77, 'Innovation', 'Innovation Culture', 'Jeff Bezos', 'Bezos says if you want innovation, you must accept failure.', 'Have I created space for failure on my team?', 'Celebrate a recent team failure and the learning that came from it.'),

-- Week 12: Legacy Building (Days 78-84)
(78, 'Legacy', 'Leadership Footprint', 'Frances Hesselbein', 'Hesselbein asks: "What do you want to be remembered for?"', 'If I left tomorrow, what would my leadership legacy be?', 'Write your leadership epitaph in 2 sentences. Is it what you want?'),
(79, 'Legacy', 'Mentoring Forward', 'Sheryl Sandberg', 'Sandberg emphasizes that mentors change lives, not just careers.', 'Whose career am I actively shaping beyond my direct reports?', 'Identify someone outside your team to mentor. Reach out today.'),
(80, 'Legacy', 'Culture Crafting', 'Ben Horowitz', 'Horowitz says culture is what happens when the CEO isn''t in the room.', 'What culture exists when I''m not present?', 'Ask someone what the team culture is like when you''re not there.'),
(81, 'Legacy', 'Systems Over Heroes', 'W. Edwards Deming', 'Deming proved that 94% of problems are system problems, not people problems.', 'Am I building systems that work without me?', 'Identify one area where you''re the bottleneck. Design a system to replace yourself.'),
(82, 'Legacy', 'Stakeholder Value', 'Larry Fink', 'Fink''s annual letters push leaders to consider all stakeholders, not just shareholders.', 'Whose interests am I serving with my leadership?', 'Map all your stakeholders. Identify one underserved group.'),
(83, 'Legacy', 'Leadership Pipeline', 'Ram Charan', 'Charan''s "Leadership Pipeline" shows leaders must produce leaders.', 'How many leaders am I developing who will develop others?', 'Identify your "leader of leaders" - someone developing other leaders.'),
(84, 'Legacy', 'Legacy Week Reflection', 'Warren Buffett', 'Buffett says "The chains of habit are too light to be felt until they are too heavy to be broken."', 'What habits am I forming today that will define my legacy?', 'Review your daily habits. Which ones serve your legacy? Which don''t?'),

-- Week 13: Integration & Mastery (Days 85-90)
(85, 'Integration', 'SIGNAL Review: Self-Awareness', 'Combined Wisdom', 'Review your self-awareness growth over the past 90 days.', 'How has my self-awareness as a leader evolved?', 'Journal about your biggest self-awareness breakthrough.'),
(86, 'Integration', 'SIGNAL Review: Influence', 'Combined Wisdom', 'Review your influence and relationship growth.', 'How has my ability to influence without authority improved?', 'Note 3 relationships that have strengthened in 90 days.'),
(87, 'Integration', 'SIGNAL Review: Growth', 'Combined Wisdom', 'Review your growth mindset development.', 'Where have I embraced discomfort for growth?', 'List 3 things you can do now that you couldn''t 90 days ago.'),
(88, 'Integration', 'SIGNAL Review: Navigation', 'Combined Wisdom', 'Review your ability to navigate complexity.', 'How do I handle uncertainty differently now?', 'Describe a recent complex situation you navigated well.'),
(89, 'Integration', 'SIGNAL Review: Authenticity & Legacy', 'Combined Wisdom', 'Review your authentic communication and legacy thinking.', 'Am I leading more authentically? What legacy am I building?', 'Ask 3 people how your leadership has changed in 90 days.'),
(90, 'Integration', 'Leadership Reboot Complete', 'Your Leadership', 'You''ve completed 90 days of intentional leadership development.', 'What kind of leader have I become? What kind do I want to continue becoming?', 'Write a letter to yourself for Day 1 of your next leadership chapter.')
ON CONFLICT (day_number) DO NOTHING;
